### PR TITLE
Add support for parentheses on import

### PR DESCRIPTION
**Pull request by williamjamir**
This PR fixes the issue #16 

@soupytwist I could not make the test pass when a space character is inserted after the import statement, but the parser runs just fine against files with space after the import, was just the test that I could not manage to work =)

File:
fromimport.in

Content:
`
from m import (n)
`
Error:
```Python
     - from m import(n)
     + from m import (n)
     ?              +
```

Do you have any clue of what this could be about?

### CODE REVIEW

**Comment by williamjamir** [comment]
I signed it!

**Comment by soupytwist** [comment]
Thanks for the PR! I didn't realize this syntax is legal actually.

This one is a bit hairy because there can be space around the parens and `optional_token` only parses a single token and note the space around it. Unfortunately I think the proper fix is a bit more involved.

I've pushed a patch to extend `scope` to handle this case. Instead of adding the `optional_token` calls, you can nest the `for` over `node.names` in:

```python
with self.scope(node, 'names'):
```

This will try to open parens when entering the `with` and then try to close them when exiting only if there is an open paren. Please make this change and see if the test case works with spaces around it!

**Comment by soupytwist** [comment]
See: 43391c1

**Comment by williamjamir** [comment]
My last commit uses the context manager to handle the parentheses.
Now both cases are passing on test =)

**Comment by soupytwist** [comment]
Thanks again!

**Pull request merged**
