### PR TITLE
Support call-style exec in python 2.7.9+

### PR DESCRIPTION
**Pull request by soupytwist**
Currently missing tests due to poor version separation. Need to test
with the revision number as well, 2.7 is not specific enough. Will
enable this separately.

### CODE REVIEW

**Comment by soupytwist** [comment]
@williamjamir, if you're able to, can you verify that this works for you on 2.7.9? I have some local configuring to do in order to get set up for many python versions. Currently I only test on 2.7.6 and 3.4.3.

**Comment by williamjamir** [comment]
Yep, with python 2.7.9 the parser identifies `exec ('x = 10', {})` correctly

```
(google_pasta_py279) william@laptop:/opt/pasta$ python --version
Python 2.7.9 :: Continuum Analytics, Inc.
```

**Comment by soupytwist** [comment]
Thanks for the quick response!

**Comment by soupytwist** [comment]
Fixed #21.

**Comment by williamjamir** [comment]
@soupytwist just for a test I added the following test on the `exec.in` and it didn't pass.

`exec(j,k)
`

**Comment by soupytwist** [comment]
Thanks, reopened #21. I misunderstood your last message.

**Comment by williamjamir** [comment]
So, running the following script:

script.py:
```
import pasta
from pasta.augment import rename

path = r'test.py'

with open(path) as file:
        tree = pasta.parse(file.read())

```
where the content from test.py is the following:
`
exec('x = 10, {})
`

Work just fine as you cann see above:

```
(google_pasta_py279) william@laptop:/opt/test_pasta$ python --version
Python 2.7.9 :: Continuum Analytics, Inc.
(google_pasta_py279) william@laptop:/opt/test_pasta$ python script.py 
(google_pasta_py279) william@laptop:/opt/test_pasta$ 
````

Whoever the test fails to execute =/

**Pull request merged**
